print('Enter the first number to add:')
first = input()
print('Enter the second number:')
second = input()
print('Enter the third number:')
third = input()
breakpoint()
print('The sum is ' + first + second + third)
